### ISSUE TITLE
Error building Foodb

### ISSUE THREAD

**Issue by QizhiSu** [joannawolthuis/MetaDBparse#2] opened 2020-09-18 17:07 UTC
Dear Joannawolthuis,
I am trying to build Foodb. However, i keep having error. 

build.FOODB(outfolder = tempdir("D:\\OneDrive\\rWorkSpace\\rHDPE"))
trying URL 'https://foodb.ca/public/system/downloads/foodb_2020_4_7_csv.tar.gz'
Content type 'application/octet-stream' length unknown
downloaded 952.5 MB

Error in data.table::fread(file = file.path(base.loc, paste0("foodb_",  : 
  File 'C:\Users\qizhi\AppData\Local\Temp\Rtmpa2Tiub/foodb_source/foodb_NA_csv/Compound.csv' does not exist or is non-readable. getwd()=='D:/OneDrive/rWorkSpace/rHDPE'

thanks in advance.
Sukis

**Comment by joannawolthuis** [comment] 2020-09-18 18:49
Hi there, thanks for your interest and bug report! That is strange, hmm...
Could you try updating the (recently available,will update the readme) CRAN version:
`install.packages("MetaDBparse")`
and see if it persists? Then I at least know we're on the same version :)

**Comment by QizhiSu** [comment] 2020-09-18 19:11
Hi, I have tried. But I still get the same error.

**Comment by joannawolthuis** [comment] 2020-09-18 19:27
Strange.. Can you confirm that the download still happened, the tar.gz file being there? Can you access this page?:
https://www.foodb.ca/downloads

**Comment by Sukis123** [comment] 2020-09-18 19:28
Yes. The files were downloaded. I can access the page as well.  Best regards,Qi-Zhi Su From: joannawolthuisSent: 2020年9月18日 21:27To: joannawolthuis/MetaDBparseCc: Sukis123; AuthorSubject: Re: [joannawolthuis/MetaDBparse] Error building Foodb (#2) Strange.. Can you confirm that the download still happened, the tar.gz file being there? Can you access this page?:https://www.foodb.ca/downloads—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by joannawolthuis** [comment] 2020-09-18 19:33
Thanks for checking! Stuff I can't reproduce always is a bit more work for you, apologies.
Can you try running the following:
```
theurl <- RCurl::getURL("https://foodb.ca/downloads", .opts = list(ssl.verifypeer = FALSE))
  version <- stringr::str_match(theurl, pattern = "FooDB Version <strong>(...)<")[, 2]
  date <- stringr::str_match(theurl, pattern = "FooDB CSV file<\\/td><td>(.{3,40})<\\/td>")[, 2]
  date <- as.Date(date, format = "%B%e%Y")
  subdate <- gsub(date, pattern = "-", replacement = "_")
  folder=file.path(base.loc, paste0("foodb_", subdate, "_csv"))
print(version)
print(date)
print(subdate)
print(folder)
```

for me?

**Comment by QizhiSu** [comment] 2020-09-18 19:34
Yes, the files were downloaded. I can access the page as well. the problem seems to be the mismatch of folder name. the downloaded and unzipped folder has name "foodb_2020_04_07_csv" while the function seems to take "foodb_NA_csv"?

**Comment by joannawolthuis** [comment] 2020-09-18 19:35
Yes that's true, it should be grabbing the date from the /downloads page, I had done that so it was flexible-ish to work with new versions. I might try a quick fix, give me a few moments:)

**Comment by QizhiSu** [comment] 2020-09-18 19:37
> theurl <- RCurl::getURL("https://foodb.ca/downloads", .opts = list(ssl.verifypeer = FALSE))
>   version <- stringr::str_match(theurl, pattern = "FooDB Version <strong>(...)<")[, 2]
>   date <- stringr::str_match(theurl, pattern = "FooDB CSV file<\\/td><td>(.{3,40})<\\/td>")[, 2]
>   date <- as.Date(date, format = "%B%e%Y")
>   subdate <- gsub(date, pattern = "-", replacement = "_")
>   folder=file.path(base.loc, paste0("foodb_", subdate, "_csv"))
> print(version)
> print(date)
> print(subdate)
> print(folder)

Don't worry. Thanks for your effort anyway. 

I have tried the code. 

![image](https://user-images.githubusercontent.com/55191839/93638173-2159e800-f9f7-11ea-879f-38ebde34bf96.png)

**Comment by joannawolthuis** [comment] 2020-09-18 19:39
Thanks, it seems specifically in your case it can't grab the current FooDB version from the downloads page. I'll fix this up and let you know when you can retry :)

**Comment by QizhiSu** [comment] 2020-09-18 19:41
thanks a lot!

**Comment by joannawolthuis** [comment] 2020-09-18 19:48
Whoops, just ment to reference it not close it, can you check if that push fixed it? :)

**Closed as completed** 2020-09-18 19:47 UTC

**Comment by QizhiSu** [comment] 2020-09-18 20:29
Don't worry. it is not closed.

**Comment by joannawolthuis** [comment] 2020-09-18 21:14
Haha:) It should be fixed now if you reinstall from GitHub! Let me know if you have similar problems with the other DBs if you don't mind.

**Comment by QizhiSu** [comment] 2020-09-18 22:16
Sorry for the delay. 
I get a new error. 
![image](https://user-images.githubusercontent.com/55191839/93649914-625cf700-fa0d-11ea-9a24-a48e4e57c937.png)
